version: '3.9'

services:
  core-service:
    container_name: cris_bank_core_service
    build:
      context: .
      target: build
    ports:
      - '${CORE_SERVICE_PORT}:${SERVICE_PORT}'
    volumes:
      - .:/app
    env_file:
      - .env
    working_dir: /app
    depends_on:
      - db
      - rabbitmq
    command: pnpm core:dev
    restart: always
    networks:
      - cris-bank-system

  transaction-service:
    container_name: cris_bank_transaction_service
    build:
      context: .
      target: build
    ports:
      - '${TRANSACTION_SERVICE_PORT}:${SERVICE_PORT}'
    volumes:
      - .:/app
    env_file:
      - .env
    working_dir: /app
    depends_on:
      - db
      - rabbitmq
    command: pnpm transaction:dev
    restart: always
    networks:
      - cris-bank-system

  db:
    container_name: cris_bank_system_mongo
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
      - MONGO_HOST
    volumes:
      - mongo-data:/data/db
    networks:
      - cris-bank-system

  db-admin:
    container_name: cris_bank_system_mongo_admin
    image: mongo-express
    restart: always
    ports:
      - $MONGO_ADMIN_PORT:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_INITDB_ROOT_USERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - ME_CONFIG_MONGODB_URL=$MONGO_URI
    depends_on:
      - db
    networks:
      - cris-bank-system

  redis:
    container_name: cris_bank_system_redis
    image: redis
    restart: always
    command: bash -c "redis-server --appendonly yes --requirepass $REDIS_PASSWORD"
    volumes:
      - redis:/data/cache
    networks:
      - cris-bank-system

  redis-gui:
    container_name: cris_bank_system_redis_gui
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOST
      - REDIS_PASSWORD
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    ports:
      - 8085:8081
    networks:
      - cris-bank-system

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: cirs_bank_system_rabbitmq
    restart: always
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - cris-bank-system

volumes:
  mongo-data:
  redis:
  rabbitmq_data:

networks:
  cris-bank-system:
    driver: bridge
